### ISSUE TITLE
Add information about required dependencies

### ISSUE THREAD

**Issue by galczo5** [clickup/ngx-esbuild#19]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Hi, to make it working on empty NX monorepository it's necessary to install `@babel/plugin-syntax-typescript` and `@babel/plugin-syntax-decorators`. 

```
✘ [ERROR] Cannot find package '@babel/plugin-syntax-typescript' imported from /Users/kamil/Dev/experiment-ngx-esbuild/babel-virtual-resolve-base.js [plugin babel]
```

```
✘ [ERROR] Cannot find package '@babel/plugin-syntax-decorators' imported from /Users/kamil/Dev/experiment-ngx-esbuild/babel-virtual-resolve-base.js [plugin babel]
```

### Minimal Reproduction

Create a new NX monorepository with Angular app
Add @clickup/ngx-esbuild
Add configuration in `project.json`
Run it

**Comment by mattlewis92** [comment]
Thanks for the bug report! This should now be fixed in `0.1.1`!
