### ISSUE TITLE
@Attribute() decorator support

### ISSUE THREAD

**Issue by galczo5** [clickup/ngx-esbuild#20]
### Description

@Attribute() decorator does not work. https://angular.io/api/core/Attribute
I checked it on an empty NX monorepository. https://github.com/galczo5/experiment-ngx-esbuild/tree/attribute-problem
You can check it using attribute-problem branch.

**Comment by mattlewis92** [comment]
Thanks for the bug report! This should now be fixed in `0.1.1`!
